import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="../styles/style.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@300&display=swap" rel="stylesheet" />
        <link rel="icon" type="image/png" href="/assets/favicon.png" />
        <link rel="shortcut icon" type="image/png" href="/assets/favicon.png" />
        <title>Encoder</title>
      </head>
      <body>
        {/* Header */}
        <header className="main-header">
          <img src="/assets/clean logo.png" alt="Logo" className="header-logo" />
          <nav className="header-nav">
            <a href="../index.html" className="nav-button">Home</a>
            <a href="./index.html" className="nav-button">Encoder</a>
            <a href="../feed.html" className="nav-button">Feed</a>
            <a href="../documentation.html" className="nav-button">Documentation</a>
          </nav>
        </header>
        {/* Main Content */}
        <main className="main-content" style={{ marginTop: 100 }}>
          {children}
        </main>
        {/* Footer */}
        <div className="content-spacer"></div>
        <footer>
          <img src="/assets/404.png" alt="404 Footer" className="footer-image" />
          <div className="footer-social-links">
            <img src="/assets/github.png" alt="GitHub" className="social-icon" />
            <img src="/assets/x.png" alt="Twitter" className="social-icon" />
          </div>
        </footer>
      </body>
    </html>
  );
}
